export const actions = {
  SET_DATA: "SET_DATA",
  DELETE_DATA:"DELETE_DATA",
  CREATE_POST:"CREATE_POST",
  CLOSE_WINDOW:"CLOSE_WINDOW",
  SET_COMMENTS:"SET_COMMENTS",
  CREATE_COMMENT:"CREATE_COMMENT",
  DELETE_COMMENT:"DELETE_COMMENT"
};




export default actions